version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"  # Перенаправление порта контейнера на порт хоста
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hardware_ecommerce
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12042003
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"  # Перенаправление порта контейнера на порт хоста
    environment:
      - MYSQL_ROOT_PASSWORD=12042003
      - MYSQL_DATABASE=hardware_ecommerce
ы